name: "DEV DEPLOY"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::058264355846:role/github-actions-infra-pipeline"
      aws-region: "us-east-1"
      aws-statefile-s3-bucket: "statefile-infra-jcosta86"
      aws-lock-dynamodb-table: "statefile-infra-jcosta86-lock"
